
const DATA_URL="data/products.json";
async function getProducts(){const r=await fetch(DATA_URL);if(!r.ok)throw Error("Product data unavailable");return r.json()}
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function setupMenu(){const b=document.querySelector('.menu-btn'),n=document.querySelector('.navlinks');if(b&&n)b.addEventListener('click',()=>n.classList.toggle('open'))}
function productCard(p){return `<article class="product-card"><a class="image" href="product.html?id=${encodeURIComponent(p.id)}"><img src="${p.image}" alt="${esc(p.name)} — ${esc(p.model)}" loading="lazy"></a><div class="card-body"><div class="product-meta"><span class="badge">${esc(p.category)}</span><span class="micro">${esc(p.model)}</span></div><h3>${esc(p.name)}</h3><p>${esc(p.description)}</p><a class="link" href="product.html?id=${encodeURIComponent(p.id)}">View product →</a></div></article>`}
function setupSearch(products){const input=document.querySelector('#product-search'),cat=document.querySelector('#category-filter'),grid=document.querySelector('#product-grid'),count=document.querySelector('#result-count');if(!input||!cat||!grid)return;const cats=[...new Set(products.map(p=>p.category))].sort();cat.innerHTML='<option value="">All product families</option>'+cats.map(c=>`<option value="${esc(c)}">${esc(c)}</option>`).join('');const requested=new URLSearchParams(location.search).get('category');if(requested&&cats.includes(requested))cat.value=requested;function render(){const q=input.value.toLowerCase().trim(),c=cat.value;const out=products.filter(p=>{const hay=[p.name,p.model,p.category,p.description,...(p.applications||[])].join(' ').toLowerCase();return(!q||hay.includes(q))&&(!c||p.category===c)});grid.innerHTML=out.length?out.map(productCard).join(''):`<div class="empty">No products matched your search. Try another term or choose another product family.</div>`;if(count)count.textContent=`${out.length} product${out.length===1?'':'s'} shown`};input.addEventListener('input',render);cat.addEventListener('change',render);render()}
function setupProductPage(products){const root=document.querySelector('#product-detail');if(!root)return;const id=new URLSearchParams(location.search).get('id'),p=products.find(x=>x.id===id);if(!p){root.innerHTML='<div class="empty">Product not found. <a class="link" href="products.html">Return to products →</a></div>';return}document.title=`${p.name} | GMC Technology`;const specs=Object.entries(p.specifications||{}).map(([k,v])=>`<tr><th>${esc(k)}</th><td>${esc(v)}</td></tr>`).join('');const related=products.filter(x=>x.category===p.category&&x.id!==p.id).slice(0,3);root.innerHTML=`<div class="detail-grid"><div><div class="detail-image"><img src="${p.image}" alt="${esc(p.name)} — ${esc(p.model)}"></div><div class="product-cta"><strong>Need a customized configuration?</strong><p class="micro">The catalogue identifies custom-made models or configurations across multiple GMC product families.</p><a class="link" href="contact.html?product=${encodeURIComponent(p.model)}">Discuss this requirement →</a></div></div><div><div class="breadcrumb"><a href="products.html">Products</a> / ${esc(p.category)}</div><span class="badge">${esc(p.category)}</span><h1>${esc(p.name)}</h1><p><strong>Model / Product code:</strong> ${esc(p.model)}</p><p class="lead">${esc(p.description)}</p>${p.applications?.length?`<h3>Applications</h3><div class="pills">${p.applications.map(a=>`<span class="pill">${esc(a)}</span>`).join('')}</div>`:''}<h3>Technical specifications</h3><table class="spec-table"><tbody>${specs}</tbody></table>${p.custom?`<div class="notice"><strong>Customization:</strong> ${esc(p.custom)}</div>`:''}<div class="actions"><a class="btn btn-primary" href="contact.html?product=${encodeURIComponent(p.model)}">Enquire about this product</a><a class="btn btn-secondary" href="documents/Catalogue-GMC.pdf">View catalogue PDF</a></div></div></div>${related.length?`<div class="section-sm"><div class="section-head"><span class="eyebrow">Related equipment</span><h2>More from this product family</h2></div><div class="product-grid">${related.map(productCard).join('')}</div></div>`:''}<a class="sticky-inquiry btn btn-gold" href="contact.html?product=${encodeURIComponent(p.model)}">Enquire: ${esc(p.model)}</a>`}
function setupEnquiry(){const form=document.querySelector('#enquiry-form');if(!form)return;const p=new URLSearchParams(location.search).get('product');if(p)document.querySelector('#product-of-interest').value=p;form.addEventListener('submit',e=>{e.preventDefault();const d=new FormData(form),subject=`GMC Technology enquiry: ${d.get('product')||'General enquiry'}`,body=[`Name: ${d.get('name')}`,`Organization: ${d.get('organization')}`,`Email: ${d.get('email')}`,`Phone: ${d.get('phone')}`,`Product: ${d.get('product')}`,`Message: ${d.get('message')}`].join('\n');location.href=`mailto:support@gmctechnology.in?cc=techgmc@gmail.com&subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`})}
document.addEventListener('DOMContentLoaded',async()=>{setupMenu();try{const products=await getProducts();setupSearch(products);setupProductPage(products)}catch(e){console.error(e)}setupEnquiry()});
